import type { MetadataRoute } from "next";
import { siteUrl } from "@/lib/seo";

const routes = [
  "/",
  "/about",
  "/about/our-mission",
  "/about/our-team",
  "/about/leadership",
  // "/about/co-founder-ceo", // hidden from nav/listings; page still exists, just not linked or indexed
  // "/about/co-founder-coo", // hidden from nav/listings; page still exists, just not linked or indexed
  // "/about/cto", // hidden from nav/listings; page still exists, just not linked or indexed
  // "/about/cfo", // hidden from nav/listings; page still exists, just not linked or indexed
  // "/about/chro", // hidden from nav/listings; page still exists, just not linked or indexed
  "/about/privacy-policy",
  "/about/terms-and-conditions",
  "/about/refund-cancellation-policy",
  "/about/acceptable-use-policy",
  "/about/success-stories",
  "/about/what-we-do",
  "/careers",
  "/careers/mern-developer",
  "/careers/genai-developer",
  "/careers/ai-ml-engineer",
  "/careers/android-app-developer",
  "/careers/ios-app-developer",
  "/careers/quality-analyst",
  "/careers/ui-ux-designer",
  "/careers/business-development-manager",
  "/careers/business-analyst",
  "/careers/project-manager",
  "/careers/bid-executive",
  "/careers/accounts-manager",
  "/careers/mis-executive",
  "/careers/hr-executive",
  "/careers/technical-content-writer",
  "/careers/digital-marketing",
  "/contact",
  "/industries",
  "/industries/healthcare",
  "/industries/ecommerce",
  "/industries/insurance",
  "/industries/agriculture",
  "/industries/education",
  "/industries/real-estate",
  "/industries/social-media",
  "/industries/travel",
  "/industries/construction",
  "/industries/hotels",
  "/industries/finance",
  "/products",
  "/products/ai-construction-platform",
  "/products/smart-spam-filter",
  "/products/ai-voice-assistant",
  "/products/predictive-analytics-engine",
  "/products/image-recognition-system",
  "/products/ai-job-board-portal",
  "/live-demos",
  "/live-demos/social-media-ai-reels-generator",
  "/services",
  "/services/ai-agent",
  "/services/ai-ml-solutions",
  "/services/ar-vr",
  "/services/desktop-app-development",
  "/services/mobile-app-development",
  "/services/prediction-and-forecasting",
  "/services/vision-intelligence",
  "/services/web-app-development",
  "/resource-augmentation",
  "/resource-augmentation/single-resource",
  "/resource-augmentation/package-based-team",
  "/resource-augmentation/hourly-on-demand",
  "/resource-augmentation/project-based",
  "/industrial-training",
  "/industrial-training/mern-stack",
  "/industrial-training/mean-stack",
  "/industrial-training/generative-ai",
  "/industrial-training/agentic-ai",
  "/industrial-training/conversational-ai",
  "/industrial-training/computer-vision",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: `${siteUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: route === "/" ? 1 : 0.7,
  }));
}
